/*
 * https://projecteuler.net/problem=2
 * Even Fibonacci numbers
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. 
 *
 * solution 1
 */

(function(){
    var n_2 = 1;
    var n_1 = 2;
    var n = n_2 + n_1;
    var result = n_1;
    
    var updateFibonacciValues = function() {
        if(n % 2 == 0)
            result += n;

        n = n_2 + n_1;
        n_2 = n_1;
        n_1 = n;
    }

    while(n <= 4000000)
        updateFibonacciValues();
 
    console.log(result);
})();
